name: Issues and Dispatches
on: [issue_comment, repository_dispatch]
env:
  CI: true
  NODE: 12.x

jobs:
  test:
    runs-on: ubuntu-latest

  steps:
    - name: Debug Action
    uses: hmarr/debug-action@v1.0.0
